import { join } from 'node:path';
import { mkdirSync } from 'node:fs';
import { writeFileAtomic } from '../fs-util.ts';
import { writeMcpJson } from './shared.ts';
import { tmuxSessionRuntime, tmuxSessionRegistry } from '../cli-sessions/tmux-session-runtime.ts';
import type { AgentCliProvider, AgentHandle, ProviderCtx, SpawnSessionOpts } from './types.ts';

function renderScriptBody(opts: SpawnSessionOpts): string {
  const isResume = opts.init.kind === 'resume';
  const isInteractive = opts.mode === 'interactive';
  const agentLabel = opts.agent ? ` agent=${opts.agent}` : '';
  const banner = isResume
    ? `[echo-stub] resume session=${opts.init.session_id}${agentLabel} prompt=${JSON.stringify(opts.prompt ?? '')}`
    : `[echo-stub] new session=${opts.init.session_id}${agentLabel} prompt=${JSON.stringify(opts.prompt ?? '')}`;
  return `// echo-stub generated script for session ${opts.init.session_id}
const fs = require('node:fs');
const path = require('node:path');
const interactive = ${JSON.stringify(isInteractive)};
process.stdout.write(${JSON.stringify(banner + '\n')});
const artifactsRoot = path.join(process.env.CLAWDEVBOX_PROJECT_DIR || '.', 'artifacts');
const artifactId = 'echo-stub-' + Date.now();
const dir = path.join(artifactsRoot, artifactId);
fs.mkdirSync(dir, { recursive: true });
const sessionId = ${JSON.stringify(opts.init.session_id)};
const prompt = ${JSON.stringify(opts.prompt ?? '')};
const agent = ${JSON.stringify(opts.agent ?? null)};
const manifest = {
  id: artifactId,
  type: 'markdown',
  title: prompt.slice(0, 80),
  workspace_id: process.env.CLAWDEVBOX_WORKSPACE_ID || null,
  recipe_instance_id: process.env.CLAWDEVBOX_RECIPE_INSTANCE_ID || null,
  step_id: null,
  created_at: Date.now(),
  meta: { entry: 'content.md', session_id: sessionId, agent },
};
fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
const body = [
  '# ' + (manifest.title || 'echo-stub'),
  '',
  'Generated by echo-stub provider.',
  '',
  '- session_id: \`' + sessionId + '\`',
  '- workspace_id: \`' + (process.env.CLAWDEVBOX_WORKSPACE_ID || '') + '\`',
  '- agent: \`' + (agent || '<none>') + '\`',
  '- resume: ' + ${JSON.stringify(isResume ? 'true' : 'false')},
  '',
  '## Prompt',
  '',
  prompt,
].join('\\n');
fs.writeFileSync(path.join(dir, 'content.md'), body);
process.stdout.write('[echo-stub] wrote artifact ' + artifactId + '\\n');
if (interactive) {
  process.stdout.write('[echo-stub] READY_FOR_DISPATCH\\n');
  const readline = require('node:readline');
  const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
  rl.on('line', (line) => {
    const trimmed = String(line).replace(/\\x1b/g, '').replace(/\\r$/, '').trim();
    if (!trimmed) return;
    if (trimmed === '__EXIT__') {
      process.stdout.write('[echo-stub] EXIT_RECEIVED\\n');
      process.exit(0);
    }
    process.stdout.write('[echo-stub] DISPATCH_RX: ' + trimmed + '\\n');
  });
  const timer = setTimeout(() => {
    process.stdout.write('[echo-stub] TIMEOUT_5M\\n');
    process.exit(0);
  }, 5 * 60 * 1000);
  timer.unref?.();
} else {
  process.exit(0);
}
`;
}

export const echoStubProvider: AgentCliProvider = {
  id: 'echo-stub',
  displayName: 'Echo Stub (testing)',
  description: 'A no-network test fixture provider. Writes a small artifact; interactive spawns stay open for dispatch smoke tests.',
  source: 'builtin',
  internal: true,
  supportsResume: false,

  async detect(_ctx: ProviderCtx) {
    return { available: true, binary: process.execPath, version: process.version };
  },

  async spawnSession(ctx: ProviderCtx, opts: SpawnSessionOpts): Promise<AgentHandle> {
    const dir = join(opts.workspaceInfo.path, '.clawdevbox', 'echo-stub');
    mkdirSync(dir, { recursive: true });
    const scriptPath = join(dir, `${opts.init.session_id}.cjs`);
    writeFileAtomic(scriptPath, renderScriptBody(opts));

    // Write .mcp.json with per-spawn headers (same pattern as claude/copilot
    // providers). echo-stub doesn't actually read the MCP config — but
    // maintaining the "every spawn writes .mcp.json" invariant simplifies the
    // test surface and matches what real CLIs see.
    writeMcpJson(ctx, opts.workspaceInfo.path, opts.mcp);

    const env = { ...process.env, ...opts.ambientEnv } as Record<string, string>;
    // Tmux-backed spawn. The agent process runs inside `tmux new-session -d -s
    // cdb_<recipeInstanceId>`; sendText/sendKey route through `tmux send-keys`
    // instead of writing to a raw pty fd.
    //
    // We prefer recipeInstanceId for the tmux session name (so /dispatch can
    // find this session by instance id) but fall back to session_id for
    // standalone spawns that aren't part of a recipe instance.
    //
    // The spawn factory is taken from ctx (allows test mocking) and falls back
    // to the tmuxSessionRuntime() singleton in production.
    const instanceKey = opts.recipeInstanceId ?? opts.init.session_id;
    const spawn = ctx.spawnTmuxSession ?? ((o) => tmuxSessionRuntime().spawn(o));
    const session = await spawn({
      name: instanceKey,
      cwd: opts.workspaceInfo.path,
      env,
      cols: opts.ptyCols ?? 80,
      rows: opts.ptyRows ?? 24,
      command: process.execPath,
      args: [scriptPath],
    });

    // Only register under recipeInstanceId so /dispatch routes match. Standalone
    // spawns without a recipe-instance id are not dispatch-addressable.
    if (opts.recipeInstanceId) {
      tmuxSessionRegistry.register(opts.recipeInstanceId, session);
    }

    return {
      pid: await session.pid(),
      sessionId: opts.init.session_id,
      session,
      exited: session.exited.then((e) => ({
        exitCode: e.exitCode ?? 0,
        signal: undefined,
      })),
    };
  },
};
