import { join } from 'node:path';
import { mkdirSync } from 'node:fs';
import { writeFileAtomic } from '../fs-util.ts';
import type { AgentCliProvider, AgentHandle, ProviderCtx, SpawnSessionOpts } from './types.ts';

function renderScriptBody(opts: SpawnSessionOpts): string {
  const isResume = opts.init.kind === 'resume';
  const agentLabel = opts.agent ? ` agent=${opts.agent}` : '';
  const banner = isResume
    ? `[echo-stub] resume session=${opts.init.session_id}${agentLabel} prompt=${JSON.stringify(opts.prompt ?? '')}`
    : `[echo-stub] new session=${opts.init.session_id}${agentLabel} prompt=${JSON.stringify(opts.prompt ?? '')}`;
  return `// echo-stub generated script for session ${opts.init.session_id}
const fs = require('node:fs');
const path = require('node:path');
process.stdout.write(${JSON.stringify(banner + '\n')});
const artifactsRoot = path.join(process.env.CLAWDEVBOX_PROJECT_DIR || '.', 'artifacts');
const artifactId = 'echo-stub-' + Date.now();
const dir = path.join(artifactsRoot, artifactId);
fs.mkdirSync(dir, { recursive: true });
const sessionId = ${JSON.stringify(opts.init.session_id)};
const prompt = ${JSON.stringify(opts.prompt ?? '')};
const agent = ${JSON.stringify(opts.agent ?? null)};
const manifest = {
  id: artifactId,
  type: 'markdown',
  title: prompt.slice(0, 80),
  workspace_id: process.env.CLAWDEVBOX_WORKSPACE_ID || null,
  recipe_instance_id: process.env.CLAWDEVBOX_RECIPE_INSTANCE_ID || null,
  step_id: null,
  created_at: Date.now(),
  meta: { entry: 'content.md', session_id: sessionId, agent },
};
fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
const body = [
  '# ' + (manifest.title || 'echo-stub'),
  '',
  'Generated by echo-stub provider.',
  '',
  '- session_id: \`' + sessionId + '\`',
  '- workspace_id: \`' + (process.env.CLAWDEVBOX_WORKSPACE_ID || '') + '\`',
  '- agent: \`' + (agent || '<none>') + '\`',
  '- resume: ' + ${JSON.stringify(isResume ? 'true' : 'false')},
  '',
  '## Prompt',
  '',
  prompt,
].join('\\n');
fs.writeFileSync(path.join(dir, 'content.md'), body);
process.stdout.write('[echo-stub] wrote artifact ' + artifactId + '\\n');
process.exit(0);
`;
}

export const echoStubProvider: AgentCliProvider = {
  id: 'echo-stub',
  displayName: 'Echo Stub (testing)',
  description: 'A no-network test fixture provider. Writes a small artifact and exits successfully.',
  source: 'builtin',
  internal: true,

  async detect(_ctx: ProviderCtx) {
    return { available: true, binary: process.execPath, version: process.version };
  },

  async spawnSession(ctx: ProviderCtx, opts: SpawnSessionOpts): Promise<AgentHandle> {
    const dir = join(opts.workspaceInfo.path, '.clawdevbox', 'echo-stub');
    mkdirSync(dir, { recursive: true });
    const scriptPath = join(dir, `${opts.init.session_id}.cjs`);
    writeFileAtomic(scriptPath, renderScriptBody(opts));

    const env = { ...process.env, ...opts.ambientEnv } as Record<string, string>;
    const pty = ctx.spawnPty(process.execPath, [scriptPath], {
      cwd: opts.workspaceInfo.path, env,
      cols: opts.ptyCols ?? 80, rows: opts.ptyRows ?? 24,
    });
    return {
      pid: pty.pid ?? null,
      sessionId: opts.init.session_id,
      pty,
      exited: new Promise((resolveExit) => pty.onExit(({ exitCode, signal }) =>
        resolveExit({ exitCode, signal: signal != null ? String(signal) : undefined }))),
    };
  },
};
